# Generated by Django 4.0.8 on 2023-12-21 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('duration', models.CharField(max_length=255)),
                ('logo_url', models.URLField(max_length=255)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('student_qty', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('active_courses', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('extra_role', models.CharField(max_length=50)),
                ('payments', models.CharField(max_length=255)),
                ('invite_people', models.IntegerField()),
                ('cashback', models.FloatField()),
                ('debt', models.FloatField()),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.courses')),
            ],
        ),
    ]
