# Generated by Django 4.0.8 on 2023-12-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_courses_logo_url_alter_users_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='tg_id',
        ),
    ]
